### PR TITLE
make header configurable

### PR DESCRIPTION
**Pull request by mhils**
Hi! Thanks for the great sphinx extension. I needed a way to configure the header and the number of columns, so here's the PR! :smiley:

example.rst

``` rst
.. documentedlist::
    :listobject: foo.lst
    :header: Surname "Given Name" Email
```

foo.py

``` python
lst = [
    ["John", "Doe", "john@example.com"]
]
```

Result

| Surname | Given Name | Email |
| --- | --- | --- |
| John | Doe | john@example.com |

### CODE REVIEW

**Comment by chintal** [comment]
Merged. I'll propagate the changes to pypi and sphinxcontrib over the next few hours. Thanks!

**Comment by mhils** [comment]
Awesome. Thanks a lot!

**Comment by chintal** [comment]
Version bumped to 0.2 on pypi and sphinxcontrib (bitbucket) with configurable header support.

**Comment by mhils** [comment]
Aaaand it's in production. Thanks for the awesomely quick response time! :smiley:

**Pull request merged**
